### ISSUE TITLE
BeautifulSoup module name changed!

### ISSUE THREAD

**Issue by talebbits** [matthewwithanm/django-html5boilerplate#6]
in BeautifulSoup==4.0b module name got changed to bs4

so at line 5 in html5boilerplate_tags.py
from BeautifulSoup import BeautifulSoup is giving 'No module named BeautifulSoup'

install_requires = ['BeautifulSoup>=3.2.0'], # TODO: Relax this requirement a bit. I'm sure it works with a much earlier version.

**Comment by matthewwithanm** [comment]
Where's my pull request? Here, I'll get you started:

```
try:
    from BeautifulSoup import BeautifulSoup
```
